# Generated by Django 4.2 on 2023-04-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=35)),
                ('price', models.IntegerField(default=0)),
                ('add_patty', models.BooleanField(default=False)),
                ('add_cheese', models.BooleanField(default=False)),
            ],
        ),
    ]
